version: '2.4'

services:
  pingpong_c:

    build:
      context: ./src
    image: pingpong_c:1.1.0
    networks:
      - proxy-redirect

    environment:
          - TOPIC_1=topic1
          - TOPIC_2=topic2
          - MQTT_USER=edge
          - MQTT_PASSWORD=edge
          - MQTT_IP=tcp://ie-databus:1883
    mem_limit: 100mb
    
    volumes:
        - './publish/:/publish/'
        - './cfg-data/:/cfg-data/'

#### Network ####

networks:
  proxy-redirect:
      external:
        name: proxy-redirect
